# Generated by Django 4.2.6 on 2023-10-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(choices=[('Завтраки', 'Завтраки'), ('Супы', 'Супы'), ('Салаты', 'Салаты'), ('Горячие блюда', 'Горячие блюда')], max_length=40, verbose_name='Категория')),
                ('name', models.CharField(max_length=257, verbose_name='Наименование')),
                ('recipe', models.TextField(verbose_name='Peцепт')),
            ],
        ),
    ]
